services:
  cp0:
    image: local/k8s-ready:dev
    container_name: k8s-cp0
    hostname: cp0
    privileged: true
    security_opt:
      - seccomp=unconfined
    tty: true
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      lab:
        aliases:
          - cp0

  worker0:
    image: local/k8s-ready:dev
    container_name: k8s-worker0
    hostname: worker0
    privileged: true
    security_opt:
      - seccomp=unconfined
    tty: true
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      lab:
        aliases:
          - worker0

networks:
  lab:
    name: lab
